dbdata:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data

db:
  image: postgres
  volumes_from:
    - dbdata

redis:
  image: redis

backend:
  build: ./backend
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  volumes:
    - ./backend:/app/backend
  environment:
    - DATABASE_HOST=db
    - RAILS_ENV=development

frontend:
  build: ./frontend
  privileged: true
  ports:
    - "80:9000"
    - "35729:35729"
  volumes:
    - ./frontend:/app/frontend
  