dbdata:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data

db:
  image: postgres
  volumes_from:
    - dbdata

backend:
  # Uncomment image for deploying and comment build
  image: faulik/kaiter_backend
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - DATABASE_HOST=db
    - RAILS_ENV=development

frontend:
  # Uncomment image for deploying and comment build
  image: faulik/kaiter_frontend
  privileged: true
  ports:
    - "80:9000"
    - "35729:35729" 