dbdata:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data

db:
  image: postgres
  volumes_from:
    - dbdata

backend:
  build: ./backend
  command: rails s -p 3000 -b 0.0.0.0
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - ./backend:/app/backend
  environment:
    - DATABASE_HOST=db
    - RAILS_ENV=development

frontend:
  build: ./frontend
  privileged: true
  ports:
    - "80:9000"
  volumes:
    - ./frontend:/app/frontend
  